// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { BezierSegmentAPI } from './beziersegment-api'
import { BezierSegment, CopyBezierSegmentToBezierSegmentAPI } from './beziersegment'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { Vector2API } from './vector2-api'

@Injectable({
  providedIn: 'root'
})
export class BezierSegmentService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  BezierSegmentServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private beziersegmentsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.beziersegmentsUrl = origin + '/api/github.com/fullstack-lang/gongthree/go/v1/beziersegments';
  }

  /** GET beziersegments from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI[]> {
    return this.getBezierSegments(GONG__StackPath, frontRepo)
  }
  getBezierSegments(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<BezierSegmentAPI[]>(this.beziersegmentsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<BezierSegmentAPI[]>('getBezierSegments', []))
      );
  }

  /** GET beziersegment by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI> {
    return this.getBezierSegment(id, GONG__StackPath, frontRepo)
  }
  getBezierSegment(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.beziersegmentsUrl}/${id}`;
    return this.http.get<BezierSegmentAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched beziersegment id=${id}`)),
      catchError(this.handleError<BezierSegmentAPI>(`getBezierSegment id=${id}`))
    );
  }

  // postFront copy beziersegment to a version with encoded pointers and post to the back
  postFront(beziersegment: BezierSegment, GONG__StackPath: string): Observable<BezierSegmentAPI> {
    let beziersegmentAPI = new BezierSegmentAPI
    CopyBezierSegmentToBezierSegmentAPI(beziersegment, beziersegmentAPI)
    const id = typeof beziersegmentAPI === 'number' ? beziersegmentAPI : beziersegmentAPI.ID
    const url = `${this.beziersegmentsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BezierSegmentAPI>(url, beziersegmentAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BezierSegmentAPI>('postBezierSegment'))
    );
  }
  
  /** POST: add a new beziersegment to the server */
  post(beziersegmentdb: BezierSegmentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI> {
    return this.postBezierSegment(beziersegmentdb, GONG__StackPath, frontRepo)
  }
  postBezierSegment(beziersegmentdb: BezierSegmentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BezierSegmentAPI>(this.beziersegmentsUrl, beziersegmentdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted beziersegmentdb id=${beziersegmentdb.ID}`)
      }),
      catchError(this.handleError<BezierSegmentAPI>('postBezierSegment'))
    );
  }

  /** DELETE: delete the beziersegmentdb from the server */
  delete(beziersegmentdb: BezierSegmentAPI | number, GONG__StackPath: string): Observable<BezierSegmentAPI> {
    return this.deleteBezierSegment(beziersegmentdb, GONG__StackPath)
  }
  deleteBezierSegment(beziersegmentdb: BezierSegmentAPI | number, GONG__StackPath: string): Observable<BezierSegmentAPI> {
    const id = typeof beziersegmentdb === 'number' ? beziersegmentdb : beziersegmentdb.ID;
    const url = `${this.beziersegmentsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<BezierSegmentAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted beziersegmentdb id=${id}`)),
      catchError(this.handleError<BezierSegmentAPI>('deleteBezierSegment'))
    );
  }

  // updateFront copy beziersegment to a version with encoded pointers and update to the back
  updateFront(beziersegment: BezierSegment, GONG__StackPath: string): Observable<BezierSegmentAPI> {
    let beziersegmentAPI = new BezierSegmentAPI
    CopyBezierSegmentToBezierSegmentAPI(beziersegment, beziersegmentAPI)
    const id = typeof beziersegmentAPI === 'number' ? beziersegmentAPI : beziersegmentAPI.ID
    const url = `${this.beziersegmentsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<BezierSegmentAPI>(url, beziersegmentAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BezierSegmentAPI>('updateBezierSegment'))
    );
  }

  /** PUT: update the beziersegmentdb on the server */
  update(beziersegmentdb: BezierSegmentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI> {
    return this.updateBezierSegment(beziersegmentdb, GONG__StackPath, frontRepo)
  }
  updateBezierSegment(beziersegmentdb: BezierSegmentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierSegmentAPI> {
    const id = typeof beziersegmentdb === 'number' ? beziersegmentdb : beziersegmentdb.ID;
    const url = `${this.beziersegmentsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<BezierSegmentAPI>(url, beziersegmentdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated beziersegmentdb id=${beziersegmentdb.ID}`)
      }),
      catchError(this.handleError<BezierSegmentAPI>('updateBezierSegment'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in BezierSegmentService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("BezierSegmentService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
