// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { BezierCurveAPI } from './beziercurve-api'
import { BezierCurve, CopyBezierCurveToBezierCurveAPI } from './beziercurve'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { BezierSegmentAPI } from './beziersegment-api'

@Injectable({
  providedIn: 'root'
})
export class BezierCurveService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  BezierCurveServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private beziercurvesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.beziercurvesUrl = origin + '/api/github.com/fullstack-lang/gongthree/go/v1/beziercurves';
  }

  /** GET beziercurves from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI[]> {
    return this.getBezierCurves(GONG__StackPath, frontRepo)
  }
  getBezierCurves(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<BezierCurveAPI[]>(this.beziercurvesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<BezierCurveAPI[]>('getBezierCurves', []))
      );
  }

  /** GET beziercurve by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI> {
    return this.getBezierCurve(id, GONG__StackPath, frontRepo)
  }
  getBezierCurve(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.beziercurvesUrl}/${id}`;
    return this.http.get<BezierCurveAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched beziercurve id=${id}`)),
      catchError(this.handleError<BezierCurveAPI>(`getBezierCurve id=${id}`))
    );
  }

  // postFront copy beziercurve to a version with encoded pointers and post to the back
  postFront(beziercurve: BezierCurve, GONG__StackPath: string): Observable<BezierCurveAPI> {
    let beziercurveAPI = new BezierCurveAPI
    CopyBezierCurveToBezierCurveAPI(beziercurve, beziercurveAPI)
    const id = typeof beziercurveAPI === 'number' ? beziercurveAPI : beziercurveAPI.ID
    const url = `${this.beziercurvesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BezierCurveAPI>(url, beziercurveAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BezierCurveAPI>('postBezierCurve'))
    );
  }
  
  /** POST: add a new beziercurve to the server */
  post(beziercurvedb: BezierCurveAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI> {
    return this.postBezierCurve(beziercurvedb, GONG__StackPath, frontRepo)
  }
  postBezierCurve(beziercurvedb: BezierCurveAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BezierCurveAPI>(this.beziercurvesUrl, beziercurvedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted beziercurvedb id=${beziercurvedb.ID}`)
      }),
      catchError(this.handleError<BezierCurveAPI>('postBezierCurve'))
    );
  }

  /** DELETE: delete the beziercurvedb from the server */
  delete(beziercurvedb: BezierCurveAPI | number, GONG__StackPath: string): Observable<BezierCurveAPI> {
    return this.deleteBezierCurve(beziercurvedb, GONG__StackPath)
  }
  deleteBezierCurve(beziercurvedb: BezierCurveAPI | number, GONG__StackPath: string): Observable<BezierCurveAPI> {
    const id = typeof beziercurvedb === 'number' ? beziercurvedb : beziercurvedb.ID;
    const url = `${this.beziercurvesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<BezierCurveAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted beziercurvedb id=${id}`)),
      catchError(this.handleError<BezierCurveAPI>('deleteBezierCurve'))
    );
  }

  // updateFront copy beziercurve to a version with encoded pointers and update to the back
  updateFront(beziercurve: BezierCurve, GONG__StackPath: string): Observable<BezierCurveAPI> {
    let beziercurveAPI = new BezierCurveAPI
    CopyBezierCurveToBezierCurveAPI(beziercurve, beziercurveAPI)
    const id = typeof beziercurveAPI === 'number' ? beziercurveAPI : beziercurveAPI.ID
    const url = `${this.beziercurvesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<BezierCurveAPI>(url, beziercurveAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BezierCurveAPI>('updateBezierCurve'))
    );
  }

  /** PUT: update the beziercurvedb on the server */
  update(beziercurvedb: BezierCurveAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI> {
    return this.updateBezierCurve(beziercurvedb, GONG__StackPath, frontRepo)
  }
  updateBezierCurve(beziercurvedb: BezierCurveAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BezierCurveAPI> {
    const id = typeof beziercurvedb === 'number' ? beziercurvedb : beziercurvedb.ID;
    const url = `${this.beziercurvesUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<BezierCurveAPI>(url, beziercurvedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated beziercurvedb id=${beziercurvedb.ID}`)
      }),
      catchError(this.handleError<BezierCurveAPI>('updateBezierCurve'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in BezierCurveService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("BezierCurveService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
